server:
  Port: :5000
  IdleTimeout: 1
  ReadTimeout: 10
  WriteTimeout: 30


postgres:
  DSN: postgres://clean:1234@localhost/clean-architecture
  PgDriver: pgx
  PgMaxOpenConns: 25
  PgMaxIdleConns: 25
  PgMaxIdleTime: 15m
